name: Push Check

on:
  push:
    branches:
      - '**'
jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Setup Node Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}

    - name: Install Dev Dependencies
      run: yarn install --production=false

    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx